/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import controladoras.AlumnoData;
import entidades.Alumno;
import static java.lang.Integer.parseInt;

/**
 *
 * @author marcel.olguin
 */
public class VistaAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaAlumnos
     */
    public VistaAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_idAlumno = new javax.swing.JTextField();
        tf_NombreAlum = new javax.swing.JTextField();
        btnBuscarPorID = new javax.swing.JButton();
        btnGuardarAlumno = new javax.swing.JButton();
        tbnBorrarAlumno = new javax.swing.JButton();
        btnActualizarAlumno = new javax.swing.JButton();
        btnLimpiarAlumno = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf_dniAlumno = new javax.swing.JTextField();
        btnBuscarPorDNI = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tf_ApellidoAlum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_FechaNacim = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_AlumActivo = new javax.swing.JRadioButton();
        btn_AlumInactivo = new javax.swing.JRadioButton();

        jLabel1.setText("Alumnos");

        jLabel2.setText("ID");

        jLabel3.setText("NOMBRE");

        tf_idAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idAlumnoActionPerformed(evt);
            }
        });

        btnBuscarPorID.setText("Buscar");
        btnBuscarPorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorIDActionPerformed(evt);
            }
        });

        btnGuardarAlumno.setText("Guardar");

        tbnBorrarAlumno.setText("Borrar");

        btnActualizarAlumno.setText("Actualizar");

        btnLimpiarAlumno.setText("Limpiar");

        jLabel6.setText("DNI");

        tf_dniAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dniAlumnoActionPerformed(evt);
            }
        });

        btnBuscarPorDNI.setText("Buscar");

        jLabel7.setText("APELLIDO");

        jLabel8.setText("FECHA DE NAC.");

        jLabel9.setText("ESTADO");

        btn_AlumActivo.setText("Activo");

        btn_AlumInactivo.setText("Inactivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarAlumno)
                        .addGap(18, 18, 18)
                        .addComponent(tbnBorrarAlumno)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_NombreAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_idAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_dniAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_ApellidoAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_FechaNacim, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_AlumActivo)
                                .addGap(18, 18, 18)
                                .addComponent(btn_AlumInactivo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActualizarAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnLimpiarAlumno)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarPorID)
                            .addComponent(btnBuscarPorDNI))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_idAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPorID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarPorDNI)
                    .addComponent(tf_dniAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_NombreAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ApellidoAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_FechaNacim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btn_AlumActivo)
                    .addComponent(btn_AlumInactivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarAlumno)
                    .addComponent(tbnBorrarAlumno)
                    .addComponent(btnActualizarAlumno)
                    .addComponent(btnLimpiarAlumno))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_idAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idAlumnoActionPerformed

    private void tf_dniAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dniAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dniAlumnoActionPerformed

    private void btnBuscarPorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorIDActionPerformed
        // TODO add your handling code here:
        /*Alumno alum= new Alumno();
        AlumnoData ad= new AlumnoData();
        
        alum = ad.buscarAlumnoPorId(parseInt(tf_idAlumno.getText()));
        if (alum!=null){
            tf_dniAlumno.setText(alum.getDni());
            tf_ApellidoAlum.setText(alum.getApellido());
            tf_NombreAlum.setText(alum.getApellido());
            tf_FechaNacim.setText(alum.getFechaNacimiento());
            if (alum.isEstado()){
                btn_AlumActivo.set
            }
           
        }*/
 
    }//GEN-LAST:event_btnBuscarPorIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarAlumno;
    private javax.swing.JButton btnBuscarPorDNI;
    private javax.swing.JButton btnBuscarPorID;
    private javax.swing.JButton btnGuardarAlumno;
    private javax.swing.JButton btnLimpiarAlumno;
    private javax.swing.JRadioButton btn_AlumActivo;
    private javax.swing.JRadioButton btn_AlumInactivo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton tbnBorrarAlumno;
    private javax.swing.JTextField tf_ApellidoAlum;
    private javax.swing.JTextField tf_FechaNacim;
    private javax.swing.JTextField tf_NombreAlum;
    private javax.swing.JTextField tf_dniAlumno;
    private javax.swing.JTextField tf_idAlumno;
    // End of variables declaration//GEN-END:variables
}
