/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import controladoras.AlumnoData;
import controladoras.InscripcionData;
import controladoras.MateriaData;
import entidades.Alumno;
import entidades.Inscripcion;
import entidades.Materia;
import java.util.HashMap;

/**
 *
 * @author marcel.olguin
 */
public class VistaInscripciones extends javax.swing.JInternalFrame {

    private MateriaData md = new MateriaData();
    private AlumnoData ad = new AlumnoData();
    private InscripcionData inData = new InscripcionData();
    private HashMap<String, Integer> alumnos = new HashMap();
    private HashMap<String, Integer> materias = new HashMap();

    /**
     * Creates new form VistaInscripciones
     */
    public VistaInscripciones() {
        initComponents();
        for (Alumno listarAlumno : ad.listarAlumnos()) {
            alumnos.put(listarAlumno.getNombre() + " " + listarAlumno.getApellido(), listarAlumno.getId_alumno());
            jComboIncripAlum.addItem(listarAlumno.getNombre() + " " + listarAlumno.getApellido());
        }
        for (Materia listarMateria : md.listarMaterias()) {
            materias.put(listarMateria.getNombre(), listarMateria.getId_materia());
            jComboIncripMateria.addItem(listarMateria.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAlumno = new javax.swing.JLabel();
        jComboIncripAlum = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboIncripMateria = new javax.swing.JComboBox<>();
        jbInscribir = new javax.swing.JButton();
        jbDesinscribir = new javax.swing.JButton();

        jLabel1.setText("FORMULARIO DE INSCRIPCION");

        lblAlumno.setText("ALUMNO");

        jLabel3.setText("MATERIA");

        jbInscribir.setText("Inscribir");
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });

        jbDesinscribir.setText("Desinscribir");
        jbDesinscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDesinscribirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jbDesinscribir))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlumno)
                            .addComponent(jLabel3))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboIncripMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboIncripAlum, 0, 171, Short.MAX_VALUE))
                            .addComponent(jbInscribir))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlumno)
                    .addComponent(jComboIncripAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboIncripMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInscribir)
                    .addComponent(jbDesinscribir))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        Alumno al; //creamos el alumno para inscribir
        Materia ma; //creamos la materia para inscribir
        String nombreAlumno = jComboIncripAlum.getSelectedItem().toString();
        String nombreMateria = jComboIncripMateria.getSelectedItem().toString();
        al = ad.buscarAlumnoPorId(alumnos.get(nombreAlumno));
        ma = md.buscarMateria(materias.get(nombreMateria));
        Inscripcion inscripcion = new Inscripcion(al, ma, 0);
        inData.inscribir(inscripcion);
    }//GEN-LAST:event_jbInscribirActionPerformed

    private void jbDesinscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDesinscribirActionPerformed
        String nombreAlumno = jComboIncripAlum.getSelectedItem().toString();
        String nombreMateria = jComboIncripMateria.getSelectedItem().toString();
        inData.borrarInscripcionMateriaAlumno(alumnos.get(nombreAlumno), materias.get(nombreMateria));
    }//GEN-LAST:event_jbDesinscribirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboIncripAlum;
    private javax.swing.JComboBox<String> jComboIncripMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbDesinscribir;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JLabel lblAlumno;
    // End of variables declaration//GEN-END:variables
}
