/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import controladoras.AlumnoData;
import entidades.Alumno;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author marcel.olguin
 */
public class VistaAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaAlumnos
     */
    public VistaAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_idAlumno = new javax.swing.JTextField();
        tf_NombreAlum = new javax.swing.JTextField();
        btnBuscarPorID = new javax.swing.JButton();
        btnGuardarAlumno = new javax.swing.JButton();
        tbnBorrarAlumno = new javax.swing.JButton();
        btnActualizarAlumno = new javax.swing.JButton();
        btnLimpiarAlumno = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf_dniAlumno = new javax.swing.JTextField();
        btnBuscarPorDNI = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tf_ApellidoAlum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_FechaNacim = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_AlumActivo = new javax.swing.JRadioButton();
        btn_AlumActivo.setEnabled(false);
        ;
        btn_AlumInactivo = new javax.swing.JRadioButton();
        btn_AlumInactivo.setEnabled(false);
        ;
        labelEstado = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(153, 255, 102));
        jLabel1.setText("Alumnos");

        jLabel2.setText("ID");

        jLabel3.setText("NOMBRE");

        tf_idAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idAlumnoActionPerformed(evt);
            }
        });

        btnBuscarPorID.setText("Buscar");
        btnBuscarPorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorIDActionPerformed(evt);
            }
        });

        btnGuardarAlumno.setText("Guardar");
        btnGuardarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAlumnoActionPerformed(evt);
            }
        });

        tbnBorrarAlumno.setText("Borrar");
        tbnBorrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnBorrarAlumnoActionPerformed(evt);
            }
        });

        btnActualizarAlumno.setText("Actualizar");
        btnActualizarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarAlumnoActionPerformed(evt);
            }
        });

        btnLimpiarAlumno.setText("Limpiar");
        btnLimpiarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAlumnoActionPerformed(evt);
            }
        });

        jLabel6.setText("DNI");

        tf_dniAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dniAlumnoActionPerformed(evt);
            }
        });

        btnBuscarPorDNI.setText("Buscar");
        btnBuscarPorDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorDNIActionPerformed(evt);
            }
        });

        jLabel7.setText("APELLIDO");

        jLabel8.setText("FECHA DE NAC.");

        jLabel9.setText("ESTADO");

        btn_AlumActivo.setText("Activo");
        btn_AlumActivo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btn_AlumActivoStateChanged(evt);
            }
        });

        btn_AlumInactivo.setText("Inactivo");
        btn_AlumInactivo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btn_AlumInactivoStateChanged(evt);
            }
        });

        labelEstado.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        labelEstado.setForeground(new java.awt.Color(0, 0, 0));
        labelEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEstado.setText("------------");
        labelEstado.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        labelEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelEstado.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarAlumno)
                        .addGap(18, 18, 18)
                        .addComponent(tbnBorrarAlumno)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_NombreAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_idAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_dniAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_ApellidoAlum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_FechaNacim, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_AlumActivo)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_AlumInactivo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(90, 90, 90)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActualizarAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnLimpiarAlumno)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarPorID)
                            .addComponent(btnBuscarPorDNI))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_idAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPorID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarPorDNI)
                    .addComponent(tf_dniAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_NombreAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ApellidoAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_FechaNacim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labelEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AlumActivo)
                    .addComponent(btn_AlumInactivo))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarAlumno)
                    .addComponent(tbnBorrarAlumno)
                    .addComponent(btnActualizarAlumno)
                    .addComponent(btnLimpiarAlumno))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_idAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idAlumnoActionPerformed

    private void tf_dniAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dniAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dniAlumnoActionPerformed

    private void btnBuscarPorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorIDActionPerformed
        // TODO add your handling code here:
       Alumno alum= new Alumno();
       AlumnoData ad= new AlumnoData();
        
        alum = ad.buscarAlumnoPorId(parseInt(tf_idAlumno.getText()));
        if (alum!=null){
            tf_dniAlumno.setText(String.valueOf(alum.getDni()));
            tf_ApellidoAlum.setText(alum.getApellido());
            tf_NombreAlum.setText(alum.getNombre());
            tf_FechaNacim.setText(alum.getFechaNacimiento().toString());
            btn_AlumActivo.setEnabled(true);
            btn_AlumInactivo.setEnabled(true);
            if (alum.isEstado()){      
                labelEstado.setOpaque(true);
                labelEstado.setBackground(new java.awt.Color(204, 204, 0));
                labelEstado.setForeground(new java.awt.Color(0, 0, 255));
                labelEstado.setText("Alumno Activo");
                //btn_AlumActivo.setSelected(true);
            }else{
                labelEstado.setForeground(Color.red);
                labelEstado.setText("Alumno Inactivo");
                //btn_AlumActivo.setSelected(false);
            } 
        }/*else{
            JOptionPane.showMessageDialog(null, "Alumno no encontrado");
        }*/
 
    }//GEN-LAST:event_btnBuscarPorIDActionPerformed
    
    private void btnBuscarPorDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorDNIActionPerformed
        
        Alumno alum = new Alumno();
        AlumnoData ad = new AlumnoData();

        alum = ad.buscarAlumnoPorDni(parseInt(tf_dniAlumno.getText()));
        if (alum != null) {
            tf_idAlumno.setText(String.valueOf(alum.getId_alumno()));
            tf_ApellidoAlum.setText(alum.getApellido());
            tf_NombreAlum.setText(alum.getNombre());
            tf_FechaNacim.setText(alum.getFechaNacimiento().toString());
            btn_AlumActivo.setEnabled(true);
            btn_AlumInactivo.setEnabled(true);
            if (alum.isEstado()) {                
                btn_AlumActivo.setSelected(true);
            } else {
                btn_AlumActivo.setSelected(false);
            }
        }/* else {
            JOptionPane.showMessageDialog(null, "Alumno no encontrado");
        }*/
        
    }//GEN-LAST:event_btnBuscarPorDNIActionPerformed

    private void btnLimpiarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarAlumnoActionPerformed
        tf_idAlumno.setText("");
        tf_dniAlumno.setText("");
        tf_ApellidoAlum.setText("");
        tf_NombreAlum.setText("");
        tf_dniAlumno.setText("");
        tf_FechaNacim.setText("");
        btn_AlumActivo.setSelected(false);
        btn_AlumInactivo.setSelected(false);
        labelEstado.setText("");
        labelEstado.setOpaque(false);        
               
    }//GEN-LAST:event_btnLimpiarAlumnoActionPerformed

    private void btnGuardarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAlumnoActionPerformed
        // TODO add your handling code here:
        Alumno alum= new Alumno();
        AlumnoData ad = new AlumnoData();
       // LocalDate fecnac = LocalDate.parse(tf_FechaNacim.getText(),DateTimeFormatter.ofPattern("yyyy-MM-dd"));

        alum.setDni(parseInt(tf_dniAlumno.getText()));
        alum.setApellido(tf_ApellidoAlum.getText());
        alum.setNombre(tf_NombreAlum.getText());
        alum.setFechaNacimiento(LocalDate.parse(tf_FechaNacim.getText(),DateTimeFormatter.ofPattern("yyyy-MM-dd")));
        alum.setEstado(true);
        ad.guardarAlumno(alum);
    }//GEN-LAST:event_btnGuardarAlumnoActionPerformed

    private void tbnBorrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnBorrarAlumnoActionPerformed
        // TODO add your handling code here:
        Alumno alum= new Alumno();
        AlumnoData ad = new AlumnoData();
        
        if (!tf_idAlumno.getText().equals("")){
            ad.eliminarAlumno(parseInt(tf_idAlumno.getText()));
        }     
    }//GEN-LAST:event_tbnBorrarAlumnoActionPerformed

    private void btnActualizarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarAlumnoActionPerformed
        // TODO add your handling code here:
        Alumno alum = new Alumno();
        AlumnoData ad = new AlumnoData();
         if (!tf_idAlumno.getText().equals("")){
             alum.setId_alumno(parseInt(tf_idAlumno.getText()));
             alum.setApellido(tf_ApellidoAlum.getText());
             alum.setNombre(tf_NombreAlum.getText());
             alum.setDni(parseInt(tf_dniAlumno.getText()));
             alum.setFechaNacimiento(LocalDate.parse(tf_FechaNacim.getText(),DateTimeFormatter.ofPattern("yyyy-MM-dd")));
             /*if (btn_AlumActivo.isSelected()) {
                 alum.setEstado(true);
             }
             if (btn_AlumInactivo.isSelected()) {;
                 alum.setEstado(false);
             }*/
             ad.modificarAlumno(alum);
         }
         
    }//GEN-LAST:event_btnActualizarAlumnoActionPerformed

    private void btn_AlumActivoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btn_AlumActivoStateChanged
        // TODO add your handling code here:
        Alumno alum=new Alumno();
        if (btn_AlumActivo.isSelected()) {
            alum.setId_alumno(parseInt(tf_idAlumno.getText()));
            btn_AlumInactivo.setSelected(false);
            
        }
    }//GEN-LAST:event_btn_AlumActivoStateChanged

    private void btn_AlumInactivoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btn_AlumInactivoStateChanged
        // TODO add your handling code here:
        if(btn_AlumInactivo.isSelected()) btn_AlumActivo.setSelected(false);
    }//GEN-LAST:event_btn_AlumInactivoStateChanged
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarAlumno;
    private javax.swing.JButton btnBuscarPorDNI;
    private javax.swing.JButton btnBuscarPorID;
    private javax.swing.JButton btnGuardarAlumno;
    private javax.swing.JButton btnLimpiarAlumno;
    private javax.swing.JRadioButton btn_AlumActivo;
    private javax.swing.JRadioButton btn_AlumInactivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JButton tbnBorrarAlumno;
    private javax.swing.JTextField tf_ApellidoAlum;
    private javax.swing.JTextField tf_FechaNacim;
    private javax.swing.JTextField tf_NombreAlum;
    private javax.swing.JTextField tf_dniAlumno;
    private javax.swing.JTextField tf_idAlumno;
    // End of variables declaration//GEN-END:variables
}
