/*
 * 
 * 
 */
package vistas;

import controladoras.AlumnoData;
import controladoras.InscripcionData;
import controladoras.MateriaData;
import entidades.Alumno;
import entidades.Inscripcion;
import entidades.Materia;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcel
 */
public class VistaMatXAlumno extends javax.swing.JInternalFrame {
    DefaultTableModel modelo;

    /**
     * Creates new form VistaAlumMat
     */
    public VistaMatXAlumno() {
        modelo=new DefaultTableModel();
        initComponents();
        armarComboBox();
        armarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMaterias = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        tf_dniAlumno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_ApellidoNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_Estado = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Materias por Alumno");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Alumno");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMaterias);

        jLabel3.setText("DNI");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre y Apellido");

        jLabel5.setText("Estado ");

        tf_Estado.setText("    ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 248, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_dniAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar))
                            .addComponent(tf_ApellidoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Estado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1)))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnBuscar)
                    .addComponent(tf_dniAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ApellidoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tf_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        //cargarTabla();
        InscripcionData listaIncrip=new InscripcionData();
        borrarFilas();
        Alumno alumno= (Alumno) jComboBox1.getSelectedItem();
        for( Inscripcion insc:listaIncrip.obtenerInscripcionesporAlumno(alumno.getId_alumno())){  
            modelo.addRow(new Object []{insc.getMateria().getId_materia(),insc.getMateria().getNombre(),insc.getNota()});
        }
    
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        Alumno alum = new Alumno();
        AlumnoData ad = new AlumnoData();
        InscripcionData listaIncrip=new InscripcionData();

        alum = ad.buscarAlumnoPorDni(parseInt(tf_dniAlumno.getText()));
        if (alum != null) {
           // tf_idAlumno.setText(String.valueOf(alum.getId_alumno()));
            tf_ApellidoNombre.setText(alum.getApellido()+", "+alum.getNombre());
//            tf_NombreAlum.setText(alum.getNombre());
//            tf_FechaNacim.setText(alum.getFechaNacimiento().toString());
//            btn_AlumActivo.setEnabled(true);
//            btn_AlumInactivo.setEnabled(true);
            if (alum.isEstado()) {                
                tf_Estado.setOpaque(true);
                tf_Estado.setBackground(new java.awt.Color(204, 204, 0));
                tf_Estado.setForeground(new java.awt.Color(0, 0, 255));
                tf_Estado.setText("Alumno Activo");
            } else {
                tf_Estado.setForeground(Color.red);
                tf_Estado.setText("Alumno Inactivo");
            }
            borrarFilas();
            for( Inscripcion insc:listaIncrip.obtenerInscripcionesporAlumno(alum.getId_alumno())){  
            modelo.addRow(new Object []{insc.getMateria().getId_materia(),insc.getMateria().getNombre(),insc.getNota()});
        }
        }       
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void armarComboBox(){
        //Alumno alumno=new Alumno();
        AlumnoData ad=new AlumnoData();
        
        for (Alumno alum: ad.listarAlumnos()) {
            Alumno alumno=new Alumno();
            alumno.setApellido(alum.getApellido());
            alumno.setNombre(alum.getNombre());
            alumno.setId_alumno(alum.getId_alumno());
            alumno.setDni(alum.getDni());
            jComboBox1.addItem(alumno);

        }
    }
    
    private void armarTabla(){
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("ID materia");
        columnas.add("Nombre");
        columnas.add("Nota");
        for(Object it:columnas){
            modelo.addColumn(it);
        }
        tablaMaterias.setModel(modelo);
    }
    
    private void borrarFilas(){
        int a=modelo.getRowCount()-1;
        for(int i=a;i>0;i--){
            modelo.removeRow(i);
        }
    }
    
    private void cargarTabla(){
        //AlumnoData ad=new AlumnoData();
        //MateriaData md=new MateriaData();
        InscripcionData listaIncrip=new InscripcionData();
        borrarFilas();
        Alumno alumno= (Alumno) jComboBox1.getSelectedItem();
        for( Inscripcion insc:listaIncrip.obtenerInscripcionesporAlumno(alumno.getId_alumno())){
            
            modelo.addRow(new Object []{insc.getMateria().getId_materia(),insc.getMateria().getNombre(),insc.getNota()});
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Alumno> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMaterias;
    private javax.swing.JTextField tf_ApellidoNombre;
    private javax.swing.JTextField tf_Estado;
    private javax.swing.JTextField tf_dniAlumno;
    // End of variables declaration//GEN-END:variables
}
